# Generated by Django 5.0.1 on 2024-05-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0002_remove_userdata_id_userdata_aboutme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='aboutme',
        ),
    ]
