# Generated by Django 5.0.1 on 2024-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0003_remove_userdata_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pic',
            field=models.FileField(default='user.jpg', upload_to='consumer_pics'),
        ),
    ]
