# Generated by Django 5.0.1 on 2024-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0004_alter_userdata_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pic',
            field=models.ImageField(default='user.jpg', upload_to='consumer_pics'),
        ),
    ]
