# Generated by Django 5.0.1 on 2024-05-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0005_alter_userdata_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
