# Generated by Django 5.0.1 on 2024-05-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0006_userdata_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('des', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=6)),
                ('pic', models.FileField(default='sad.jpg', upload_to='products_images')),
            ],
        ),
    ]
