# Generated by Django 5.0.1 on 2024-05-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.userdata')),
            ],
        ),
    ]
