# Generated by Django 5.0.1 on 2024-05-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
