# Generated by Django 5.0.1 on 2024-05-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
