# Generated by Django 5.0.1 on 2024-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0012_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
